name: "Api Doc Crafter"
description: "Clean, Merge, Group, Remove and generate OpenAPI documentation."
author: "Yuna Morgenstern"
inputs:
  swagger_js:
    description: "[PATH] (local=no external resource) Path to the Swagger JS file."
    required: false
  swagger_bundle_js:
    description: "[PATH] (local=no external resource) Path to the Swagger JS file."
    required: false
  swagger_css:
    description: "[PATH] (local=no external resource) Path to the Swagger CSS file."
    required: false
  swagger_favicon:
    description: "[PATH] (local=no external resource) Path to the Swagger favicon png file."
    required: false
  swagger_logo:
    description: "[PATH] (local=no external resource) Path to the Swagger logo file."
    required: false
  swagger_nav:
    description: "[BOOL] Generate navigation"
    required: false
  swagger_links:
    description: "[BOOL] Generate download source links"
    required: false
  work_dir:
    description: "[PATH] Working directory for the input files."
    required: true
    default: "."
  output_dir:
    description: "[PATH] Directory to save the output files."
    required: false
    default: "./swagger_output"
  file_download:
    description: "[Path] Download external files. Separated by or `||`. (`https://petstore.swagger.io/v2/swagger.json`)"
    required: false
  file_download_header:
    description: "[Map] Download request header separated by or `||` and `->` (`Auth->token||x-trace-id->2008`)"
  file_includes:
    description: "[GLOB] File patterns to include. GLOB patterns separated by '::' or '|'."
    required: false
  file_excludes:
    description: "[GLOB] File patterns to exclude. GLOB patterns separated by '::' or '|'."
    required: false
  max_deep:
    description: "[INT] Maximum directory depth to search."
    required: false
    default: "100"
  sort_extensions:
    description: "[BOOL] Sort OpenAPI extensions alphabetically."
    required: false
  sort_servers:
    description: "[BOOL] Sort OpenAPI servers alphabetically."
    required: false
  sort_security:
    description: "[BOOL] Sort OpenAPI security schemes alphabetically."
    required: false
  sort_tags:
    description: "[BOOL] Sort OpenAPI tags alphabetically."
    required: false
  sort_paths:
    description: "[BOOL] Sort OpenAPI paths alphabetically."
    required: false
  sort_schemas:
    description: "[BOOL] Sort OpenAPI schemas alphabetically."
    required: false
  sort_parameters:
    description: "[BOOL] Sort OpenAPI parameters alphabetically."
    required: false
  sort_responses:
    description: "[BOOL] Sort OpenAPI responses alphabetically."
    required: false
  sort_examples:
    description: "[BOOL] Sort OpenAPI examples alphabetically."
    required: false
  sort_webhooks:
    description: "[BOOL] Sort OpenAPI webhooks alphabetically."
    required: false
  sort_headers:
    description: "[BOOL] Sort OpenAPI headers alphabetically."
    required: false
  sort_scopes:
    description: "[BOOL] Sort OpenAPI scopes alphabetically."
    required: false
  sort_requests:
    description: "[BOOL] Sort OpenAPI requests alphabetically."
    required: false
  sort_content:
    description: "[BOOL] Sort OpenAPI content alphabetically."
    required: false
  sort_encoding:
    description: "[BOOL] Sort OpenAPI encodings alphabetically."
    required: false
  remove_patterns:
    description: "[GLOB] Keys or fields to remove from OpenAPI files. Separate servers with '::' or '|'."
    required: false
  group_tags:
    description: "[GLOB] Group OpenAPI files by tags. Separate tags with '::', '|', or ','."
    required: false
  group_servers:
    description: "[GLOB] Group OpenAPI files by servers. Separate servers with '::' or '|'."
    required: false
outputs:
  output_path:
    description: "Path of the generated files."
runs:
  using: "docker"
  image: "docker://ghcr.io/yunabraska/api-doc-crafter:latest"
  env:
    ADC_SWAGGER_JS: ${{ inputs.swagger_js }}
    ADC_SWAGGER_BUNDLE_JS: ${{ inputs.swagger_bundle_js }}
    ADC_SWAGGER_CSS: ${{ inputs.swagger_css }}
    ADC_SWAGGER_FAVICON: ${{ inputs.swagger_favicon }}
    ADC_SWAGGER_LOGO: ${{ inputs.swagger_logo }}
    ADC_SWAGGER_NAV: ${{ inputs.swagger_nav }}
    ADC_SWAGGER_LINKS: ${{ inputs.swagger_links }}
    ADC_OUTPUT_DIR: ${{ inputs.output_dir }}
    ADC_WORK_DIR: ${{ inputs.work_dir }}
    ADC_FILE_DOWNLOAD: ${{ inputs.file_download }}
    ADC_FILE_DOWNLOAD_HEADER: ${{ inputs.file_download_header }}
    ADC_FILE_INCLUDES: ${{ inputs.file_includes }}
    ADC_FILE_EXCLUDES: ${{ inputs.file_excludes }}
    ADC_MAX_DEEP: ${{ inputs.max_deep }}
    ADC_SORT_EXTENSIONS: ${{ inputs.sort_extensions }}
    ADC_SORT_SERVERS: ${{ inputs.sort_servers }}
    ADC_SORT_SECURITY: ${{ inputs.sort_security }}
    ADC_SORT_TAGS: ${{ inputs.sort_tags }}
    ADC_SORT_PATHS: ${{ inputs.sort_paths }}
    ADC_SORT_SCHEMAS: ${{ inputs.sort_schemas }}
    ADC_SORT_PARAMETERS: ${{ inputs.sort_parameters }}
    ADC_SORT_RESPONSES: ${{ inputs.sort_responses }}
    ADC_SORT_EXAMPLES: ${{ inputs.sort_examples }}
    ADC_SORT_WEBHOOKS: ${{ inputs.sort_webhooks }}
    ADC_SORT_HEADERS: ${{ inputs.sort_headers }}
    ADC_SORT_SCOPES: ${{ inputs.sort_scopes }}
    ADC_SORT_REQUESTS: ${{ inputs.sort_requests }}
    ADC_SORT_CONTENT: ${{ inputs.sort_content }}
    ADC_SORT_ENCODING: ${{ inputs.sort_encoding }}
    ADC_REMOVE_PATTERNS: ${{ inputs.remove_patterns }}
    ADC_GROUP_TAGS: ${{ inputs.group_tags }}
    ADC_GROUP_SERVERS: ${{ inputs.group_servers }}
branding:
  color: "green"
  icon: "code"
